# Generated by Django 4.2.1 on 2023-05-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MindsetApp', '0002_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindsetApp.disease')),
            ],
        ),
    ]
