# Generated by Django 4.2.1 on 2023-05-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MindsetApp', '0003_questions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='disease',
            table='MindsetApp_disease',
        ),
        migrations.AlterModelTable(
            name='questions',
            table='MindsetApp_questions',
        ),
        migrations.AlterModelTable(
            name='user',
            table='MindsetApp_user',
        ),
    ]
