# Generated by Django 4.2.1 on 2023-05-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MindsetApp', '0005_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('always', models.IntegerField()),
                ('often', models.IntegerField()),
                ('sometimes', models.IntegerField()),
                ('none', models.IntegerField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindsetApp.patient')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindsetApp.questions')),
            ],
            options={
                'db_table': 'MindsetApp_output',
            },
        ),
    ]
