# Generated by Django 4.2.1 on 2023-05-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MindsetApp', '0007_alter_output_always_alter_output_none_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='always',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='output',
            name='none',
        ),
        migrations.RemoveField(
            model_name='output',
            name='often',
        ),
        migrations.RemoveField(
            model_name='output',
            name='sometimes',
        ),
    ]
