# Generated by Django 4.2.1 on 2023-05-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindsetApp', '0012_chatroom_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'MindsetApp_contact',
            },
        ),
        migrations.AlterModelTable(
            name='chat',
            table='MindsetApp_chat',
        ),
    ]
