# Generated by Django 4.2.1 on 2023-05-25 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MindsetApp', '0015_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MindsetApp.disease'),
        ),
    ]
