# Generated by Django 4.2.1 on 2023-05-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MindsetApp', '0016_output_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='disease',
        ),
        migrations.AddField(
            model_name='output',
            name='disease_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MindsetApp.disease'),
        ),
    ]
