# Generated by Django 4.2.1 on 2023-05-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MindsetApp', '0017_remove_output_disease_output_disease_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='disease_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindsetApp.disease'),
        ),
    ]
